export default {
  id: "canonical",
  title: "Why ours is the generation",
  description: "The full 20-minute arc. Cosmic scale → hidden history → why now.",
  runtime: 20,
  slides: [
    {
      id: 1,
      kind: "cover-quiet",
      eyebrow: "",
      title: "A pale blue dot.",
      body: "Everyone you have ever known lived out their lives here.",
      footnote: "Voyager 1 · 6 billion km · 1990",
      image: "https://images-assets.nasa.gov/image/PIA00452/PIA00452~orig.jpg",
    },
    {
      id: 2,
      kind: "title",
      eyebrow: "A talk in three acts",
      title: "Why ours is the generation.",
      body: "Cosmic scale. A hidden history. And a question we can no longer avoid.",
      footnote: "Press → to begin",
    },
    {
      id: 3,
      kind: "content",
      eyebrow: "Act I · The cosmic address",
      title: "Our neighborhood is crowded.",
      body: "Within 10 light-years of Earth there are roughly a dozen stars. Within 50, there are more than 1,400. We are not floating alone in the dark — we are in a dense, well-lit room.",
      footnote: "Source: RECONS / NASA",
    },
    {
      id: 4,
      kind: "content",
      eyebrow: "How we find them",
      title: "Transits and wobbles.",
      body: "We watch stars dim as planets pass in front of them. We watch stars wobble as planets tug on them. That is almost the entire trick — and it works.",
      footnote: "Transit photometry · radial velocity",
    },
    {
      id: 5,
      kind: "stat",
      eyebrow: "The curve that changed everything",
      title: "5 → 5,800+",
      body: "Confirmed exoplanets known in 1995 versus today. Thirty years ago, zero were confirmed around sun-like stars. Now we find them faster than we can name them.",
      footnote: "NASA Exoplanet Archive",
    },
    {
      id: 6,
      kind: "content",
      eyebrow: "And we've barely looked",
      title: "We found all of that through a straw.",
      body: "Kepler stared at one patch of sky the size of your fist held at arm's length. TESS is surveying more — but a fraction of one percent of the galaxy has been meaningfully searched for planets.",
      footnote: "Kepler field · ~0.25% of the sky",
    },
    {
      id: 7,
      kind: "stat",
      eyebrow: "Scaling up",
      title: "~300,000,000",
      body: "NASA's best estimate of potentially habitable, Earth-sized planets around sun-like stars in the Milky Way alone. Three hundred million Goldilocks candidates. In one galaxy. Out of two trillion.",
      footnote: "Bryson et al., 2021 · The Astronomical Journal",
    },
    {
      id: 8,
      kind: "clip",
      eyebrow: "Interlude",
      title: "Clip 1 — Kepler field flyover",
      body: "Drop your video file here or embed a YouTube URL. ~60 seconds. Visual, not talking-head.",
      footnote: "src=\"/clips/kepler-flyover.mp4\"",
    },
    {
      id: 9,
      kind: "pivot",
      eyebrow: "Act II · A hidden history",
      title: "So — have any of them visited?",
      body: "Here is where most serious talks end. We are going to keep going. But only with things that are on the public record, under oath, or from named witnesses.",
    },
    {
      id: 10,
      kind: "content",
      eyebrow: "The long record",
      title: "Bronze Age to Kenneth Arnold.",
      body: "Humans have told stories about anomalous things in the sky for as long as we have told stories. In 1947, a pilot named Kenneth Arnold saw nine objects over Mount Rainier. The modern era begins there.",
      footnote: "Arnold sighting · June 24, 1947",
    },
    {
      id: 11,
      kind: "content",
      eyebrow: "The pattern nobody wanted",
      title: "UFOs have a thing for nukes.",
      body: "Researcher Robert Hastings has collected testimony from more than 150 former U.S. military personnel describing UAP incidents at nuclear weapons sites. In 2010, seven of them testified together at the National Press Club. Malmstrom AFB, 1967: ten ICBMs went offline during a sighting.",
      footnote: "Hastings · UFOs and Nukes · 2010 Press Club",
    },
    {
      id: 12,
      kind: "content",
      eyebrow: "The convert",
      title: "J. Allen Hynek changed his mind.",
      body: "Hired by the Air Force to debunk sightings for Project Blue Book, Hynek spent twenty years as the program's chief skeptic. Then he quietly stopped being one. By the 1970s he was arguing the phenomenon was real and the investigation had been a joke.",
      footnote: "Project Blue Book · 1952–1969",
    },
    {
      id: 13,
      kind: "content",
      eyebrow: "The modern disclosure era",
      title: "2017 → 2023.",
      body: "The New York Times breaks AATIP. Luis Elizondo resigns and goes public. Chris Mellon follows. In July 2023, former intelligence officer David Grusch testifies under oath to Congress that multiple witnesses told him the U.S. possesses non-human craft. The UAP Disclosure Act passes — with its teeth removed.",
      footnote: "NYT Dec 2017 · Grusch testimony Jul 2023 · UAPDA 2023",
    },
    {
      id: 14,
      kind: "clip",
      eyebrow: "Interlude",
      title: "Clip 2 — Grusch testimony or Navy FLIR",
      body: "~60 seconds of the most credible on-camera moment you can find. Let it breathe. Don't talk over it.",
      footnote: "src=\"/clips/grusch-excerpt.mp4\"",
    },
    {
      id: 15,
      kind: "content",
      eyebrow: "What is actually being described",
      title: "The Five Observables.",
      body: "Anti-gravity lift. Sudden and instantaneous acceleration. Hypersonic velocity without signatures. Low observability. Trans-medium travel. Hal Puthoff and Eric Davis have spent decades arguing these are not misidentifications — they are a physics problem.",
      footnote: "Puthoff / Davis · see also the alleged Wilson-Davis memo",
    },
    {
      id: 16,
      kind: "content",
      eyebrow: "Act III · Why now",
      title: "The anti-Turing moment.",
      body: "We are weeks, not years, from a world where no photograph, no video, no audio recording can be trusted on its face. The window in which physical evidence could still convince a skeptical public is closing. If disclosure doesn't happen before it shuts, it may never happen at all.",
    },
    {
      id: 17,
      kind: "content-heavy",
      eyebrow: "The knife's edge",
      title: "We have godlike tools and stone-age wisdom.",
      body: "Nuclear arsenals on hair-trigger. Institutions the public no longer trusts. A paper published in a peer-reviewed astrobiology journal (Schmidt & Frank, 2018) seriously asks whether we would even be able to tell if a prior industrial civilization had existed on Earth. The answer is: probably not. We are not guaranteed to be the first. We are not guaranteed to be the last.",
      footnote: "Schmidt & Frank · Silurian Hypothesis · Int. J. Astrobiology",
    },
    {
      id: 18,
      kind: "cover-quiet",
      eyebrow: "Finale",
      title: "Hope is a discipline.",
      body: "If any of this is real, it is the largest story in human history — and it may also be the catalyst we need to grow up. To build sustainable systems. To remember we share one small rock. The conversation itself is the beginning. Thank you.",
      footnote: "— end —",
    },
  ],
};
